### ISSUE TITLE
Look into Websocket handshake error.

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/multiplayer-phone-game#30]
This error doesn't occur locally, only on play.smm.org. It does not break the game, but it worth diving into.

from /screen.html

`WebSocket connection to 'wss://play.smm.org/socket.io/?EIO=3&transport=websocket&sid=o0hT0nUFk2VndtgbAAAi' failed: Error during WebSocket handshake: Unexpected response code: 400`

Possibly related to https?
https://github.com/miguelgrinberg/Flask-SocketIO/issues/401

**Comment by bryankennedy** [comment]
This seems like it's related to our websocket proxy pass setup.

I was able to fix this by adjusting our Apache settings following the instructions in this answer:
https://stackoverflow.com/a/41685748

@tnordberg I've deployed the full version at this point and it looks like it's fixed on play.smm.org.

Moving to QA. Close if you can confirm.

**Comment by bryankennedy** [comment]
We haven't seen this error recently, marking closed.
