### ISSUE TITLE
ua-parser is insecure

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/multiplayer-phone-game#35]
The version of ua-parser we're importing has a security issue. Upgrade to fix.

**Comment by bryankennedy** [comment]
I got this wrong, the bug is still active:
https://www.npmjs.com/advisories/316

We need to switch to another package to address this. I'll look at whether we can easily switch [useragent](https://www.npmjs.com/package/useragent)

**Comment by bryankennedy** [comment]
@tnordberg I switched to a different module to display the UA info in the console. Take a look and make sure that the data is showing up correctly for you. If this works, please close the issue.

**Comment by tnordberg** [comment]
Thanks @bryankennedy, I tested and the user agent data is still coming through as expected. Closing.
